/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as AppProjectsProjectIdVideoRouteImport } from './routes/_app.projects.$projectId.video'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app.projects.$projectId.settings'
import { Route as AppProjectsProjectIdReviewsRouteImport } from './routes/_app.projects.$projectId.reviews'
import { Route as AppProjectsProjectIdLibraryRouteImport } from './routes/_app.projects.$projectId.library'
import { Route as AppProjectsProjectIdDesignRouteImport } from './routes/_app.projects.$projectId.design'
import { Route as AppProjectsProjectIdPropsPropIdRouteImport } from './routes/_app.projects.$projectId.props.$propId'
import { Route as AppProjectsProjectIdGeneratePropRouteImport } from './routes/_app.projects.$projectId.generate.prop'
import { Route as AppProjectsProjectIdGenerateCharacterRouteImport } from './routes/_app.projects.$projectId.generate.character'
import { Route as AppProjectsProjectIdCharactersCharacterIdRouteImport } from './routes/_app.projects.$projectId.characters.$characterId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdVideoRoute =
  AppProjectsProjectIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdReviewsRoute =
  AppProjectsProjectIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdLibraryRoute =
  AppProjectsProjectIdLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDesignRoute =
  AppProjectsProjectIdDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdPropsPropIdRoute =
  AppProjectsProjectIdPropsPropIdRouteImport.update({
    id: '/props/$propId',
    path: '/props/$propId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdGeneratePropRoute =
  AppProjectsProjectIdGeneratePropRouteImport.update({
    id: '/generate/prop',
    path: '/generate/prop',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdGenerateCharacterRoute =
  AppProjectsProjectIdGenerateCharacterRouteImport.update({
    id: '/generate/character',
    path: '/generate/character',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdCharactersCharacterIdRoute =
  AppProjectsProjectIdCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/design': typeof AppProjectsProjectIdDesignRoute
  '/projects/$projectId/library': typeof AppProjectsProjectIdLibraryRoute
  '/projects/$projectId/reviews': typeof AppProjectsProjectIdReviewsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/video': typeof AppProjectsProjectIdVideoRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/characters/$characterId': typeof AppProjectsProjectIdCharactersCharacterIdRoute
  '/projects/$projectId/generate/character': typeof AppProjectsProjectIdGenerateCharacterRoute
  '/projects/$projectId/generate/prop': typeof AppProjectsProjectIdGeneratePropRoute
  '/projects/$projectId/props/$propId': typeof AppProjectsProjectIdPropsPropIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/design': typeof AppProjectsProjectIdDesignRoute
  '/projects/$projectId/library': typeof AppProjectsProjectIdLibraryRoute
  '/projects/$projectId/reviews': typeof AppProjectsProjectIdReviewsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/video': typeof AppProjectsProjectIdVideoRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/characters/$characterId': typeof AppProjectsProjectIdCharactersCharacterIdRoute
  '/projects/$projectId/generate/character': typeof AppProjectsProjectIdGenerateCharacterRoute
  '/projects/$projectId/generate/prop': typeof AppProjectsProjectIdGeneratePropRoute
  '/projects/$projectId/props/$propId': typeof AppProjectsProjectIdPropsPropIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/design': typeof AppProjectsProjectIdDesignRoute
  '/_app/projects/$projectId/library': typeof AppProjectsProjectIdLibraryRoute
  '/_app/projects/$projectId/reviews': typeof AppProjectsProjectIdReviewsRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/video': typeof AppProjectsProjectIdVideoRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/characters/$characterId': typeof AppProjectsProjectIdCharactersCharacterIdRoute
  '/_app/projects/$projectId/generate/character': typeof AppProjectsProjectIdGenerateCharacterRoute
  '/_app/projects/$projectId/generate/prop': typeof AppProjectsProjectIdGeneratePropRoute
  '/_app/projects/$projectId/props/$propId': typeof AppProjectsProjectIdPropsPropIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/design'
    | '/projects/$projectId/library'
    | '/projects/$projectId/reviews'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/video'
    | '/projects/$projectId/'
    | '/projects/$projectId/characters/$characterId'
    | '/projects/$projectId/generate/character'
    | '/projects/$projectId/generate/prop'
    | '/projects/$projectId/props/$propId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId/design'
    | '/projects/$projectId/library'
    | '/projects/$projectId/reviews'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/video'
    | '/projects/$projectId'
    | '/projects/$projectId/characters/$characterId'
    | '/projects/$projectId/generate/character'
    | '/projects/$projectId/generate/prop'
    | '/projects/$projectId/props/$propId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/projects'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/projects/'
    | '/_app/projects/$projectId/design'
    | '/_app/projects/$projectId/library'
    | '/_app/projects/$projectId/reviews'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/video'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/characters/$characterId'
    | '/_app/projects/$projectId/generate/character'
    | '/_app/projects/$projectId/generate/prop'
    | '/_app/projects/$projectId/props/$propId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/video': {
      id: '/_app/projects/$projectId/video'
      path: '/video'
      fullPath: '/projects/$projectId/video'
      preLoaderRoute: typeof AppProjectsProjectIdVideoRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/reviews': {
      id: '/_app/projects/$projectId/reviews'
      path: '/reviews'
      fullPath: '/projects/$projectId/reviews'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/library': {
      id: '/_app/projects/$projectId/library'
      path: '/library'
      fullPath: '/projects/$projectId/library'
      preLoaderRoute: typeof AppProjectsProjectIdLibraryRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/design': {
      id: '/_app/projects/$projectId/design'
      path: '/design'
      fullPath: '/projects/$projectId/design'
      preLoaderRoute: typeof AppProjectsProjectIdDesignRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/props/$propId': {
      id: '/_app/projects/$projectId/props/$propId'
      path: '/props/$propId'
      fullPath: '/projects/$projectId/props/$propId'
      preLoaderRoute: typeof AppProjectsProjectIdPropsPropIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/generate/prop': {
      id: '/_app/projects/$projectId/generate/prop'
      path: '/generate/prop'
      fullPath: '/projects/$projectId/generate/prop'
      preLoaderRoute: typeof AppProjectsProjectIdGeneratePropRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/generate/character': {
      id: '/_app/projects/$projectId/generate/character'
      path: '/generate/character'
      fullPath: '/projects/$projectId/generate/character'
      preLoaderRoute: typeof AppProjectsProjectIdGenerateCharacterRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/characters/$characterId': {
      id: '/_app/projects/$projectId/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/projects/$projectId/characters/$characterId'
      preLoaderRoute: typeof AppProjectsProjectIdCharactersCharacterIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdDesignRoute: typeof AppProjectsProjectIdDesignRoute
  AppProjectsProjectIdLibraryRoute: typeof AppProjectsProjectIdLibraryRoute
  AppProjectsProjectIdReviewsRoute: typeof AppProjectsProjectIdReviewsRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdVideoRoute: typeof AppProjectsProjectIdVideoRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdCharactersCharacterIdRoute: typeof AppProjectsProjectIdCharactersCharacterIdRoute
  AppProjectsProjectIdGenerateCharacterRoute: typeof AppProjectsProjectIdGenerateCharacterRoute
  AppProjectsProjectIdGeneratePropRoute: typeof AppProjectsProjectIdGeneratePropRoute
  AppProjectsProjectIdPropsPropIdRoute: typeof AppProjectsProjectIdPropsPropIdRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdDesignRoute: AppProjectsProjectIdDesignRoute,
  AppProjectsProjectIdLibraryRoute: AppProjectsProjectIdLibraryRoute,
  AppProjectsProjectIdReviewsRoute: AppProjectsProjectIdReviewsRoute,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdVideoRoute: AppProjectsProjectIdVideoRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdCharactersCharacterIdRoute:
    AppProjectsProjectIdCharactersCharacterIdRoute,
  AppProjectsProjectIdGenerateCharacterRoute:
    AppProjectsProjectIdGenerateCharacterRoute,
  AppProjectsProjectIdGeneratePropRoute: AppProjectsProjectIdGeneratePropRoute,
  AppProjectsProjectIdPropsPropIdRoute: AppProjectsProjectIdPropsPropIdRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsRoute: AppProjectsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
